import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/Navbar';
import { clsx } from 'clsx';
import AuthContext from '@/context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(clsx(inter.className), 'w-full w-screen-xl oveflow-auto mx-auto')}>
        <AuthContext>
          <header className="sticky top-0 bg-white z-10 border-b">
            <NavBar />
          </header>
          <body>{children}</body>
        </AuthContext>
      </body>
    </html>
  );
}
